### ISSUE TITLE
Convergence order for Modified Runge-Kutta method fourth order

### ISSUE THREAD

**Issue by Vanitha83** [Vanitha83/CompAlgorithms#1]
// Modified Euler for order convergence(reset):
// Check the order of convergence ( spike is included ):
//
#include<stdio.h>
#include<math.h>
#include<stdlib.h>
double function1(double t,double v,double g);
double function2(double t,double v, double dt,double g, double *v0t, double tspike, int n);
void eulersmethod(double t, double dt,double geuler[], double euler[], double s[], int n); // membrane potential is passed as an array :
//
int main()
{
    
// 
    int i,j;
    const int n = 128;
    double pi = 4*atan(1.0);
    double t;
    double Error[n][3], error[n][3];
    double euler[n],v0;
    double geuler[n];
    double dt[3];
    double sigma = 6.0;
    for (int i=0; i<3; i++)
    {
		dt[i]=0.001*pow(10,(-(i+1))); 
    }
//
  
    char file_name[n]="euler.dat";	
    FILE *fp;
    fp=fopen(file_name,"w");           
    if(fp==NULL)
    { 
		printf(" File - Open Error\n");
		return 0;
    }
    double T = 10; // in seconds :
    double s[n]; 
//
// set up gaussian profile:
//
    for(i=0;i<=n-1;i++)
    {
        s[i] = 1/(sigma*sqrt(2*pi))*exp(-i*i/(2*sigma*sigma));      
    }
	v0 = 0;
//
	for(int idt=0;idt<3;idt++)  // for different timesteps dt1 = 0.1 and dt2 = 0.0001://
	{
// initialize before different timestep
        printf("%d\n" , idt);

  		for(i=0;i<=n-1;i++)
	   	{
	   		euler[i] = v0;		   
	   	}
	   	for(i=0;i<=n-1;i++)
	   	{
		  		geuler[i] = 0.0;   
	   	}
// start time loop :
	 	for(t=0;t<T;t=t+dt[idt])               // Increment in time and integrate till T=1 second :
	 	{
		
	        	eulersmethod(t,dt[idt],geuler,euler,s,n);
	 	}
	 	for (i=0; i<n-1; i++)
       {
				Error[i][idt]=euler[i];        // store the membrane potential :
	    }
  	}

   	for (int idt=0;idt<2;idt++){               // loop for the time step
		//printf("%d\t| %d\t %.10lf\t - %.10lf\n", idt,1, Error[1][idt],Error[1][2]);
		for (i=0; i<n; i++){
			Error[i][idt]=(Error[i][idt]-Error[i][2]); // difference between potential and the canonical at the final time :
            if (Error[i][idt] < 0) {
				Error[i][idt] = Error[i][idt] * (-1);
    
			}	
		  	error[i][idt]=log10(Error[i][idt]);
            fprintf(fp,"%lf\t%.10lf\n",log10(dt[idt]), error[i][idt]); 
            
		}
	//	printf("%d\t| %d\t %.10lf\t %.10lf\n", idt,1, Error[1][idt],error[1][idt]);
            
        	
        
	}

	fclose(fp);
	return 0;       
}
// Function 1 :
//
double function1(double t, double v,double g) 
{
    
    int i;
    double alpha0,beta0,vdot,c=1;
    
            alpha0 = (50)+(1/c)*(50*sin(t)+g);	
            beta0 = (1/c)*(14.0/3.0)*(50*sin(t)+g);
            vdot= -alpha0*v+beta0;
            return vdot;
 
}
// Function 2:
//
double function2(double t, double v, double dt,double g,double *v0t,double tspike, int n)
{
   
    int i;
    double alpha0,beta0,alpha1,beta1,v1dot,c=1,vth,vreset;
    vth =1;
    vreset = 0;
            
           
            alpha0 = 50+(1/c)*(50*sin(t)+g);
            beta0  = (1/c)*(14/3.0)*(50*sin(t)+g);
            //alpha1 = 50+(1/c)*(50*sin(t+dt)+g); // estimate the new conductance value for alpha1 and beta1 :
            //beta1 = (1/c)*(14/3.0)*(50*sin(t+dt)+g); 
            *v0t = vreset-(beta0/(1+alpha0))*tspike; // vntilda for modified euler :
            v1dot = -alpha0*(*v0t)+beta0;
            return v1dot;

}
//
void eulersmethod(double t, double dt,double geuler[], double euler[],double s[], int n)
{
//The Euler scheme with time stepsize dt :

    double k1,k2,m1,m2,v1,tn,tspike,alpha0,beta0,vth,vreset,tau,v0t;
    double c;
    int i,j,k;
    double G[n];
    double v0;
    tau = 0.6;   // fix this for this run:
    vth = 1;    //  spike threshold potential in mv :
    vreset =0;  //  reset voltage after spiking in mv:
    tspike=0;
    int numspikes = 0;
//
  	for(k=0;k<=n-1;k++)
  	{
       		G[k]=0.0;   
   	}
    for(i=0;i<=n-1;i++)  // for n neurons :
    {
		 v0 = euler[i];
		 k1 = function1(t,v0,geuler[i]); 
		 v1  =v0+dt*k1;                                  
         //printf("Before spiking: %lf\n",v1);
         if(v1>vth){
         tspike = (vth-v0)/(v1-v0)*dt;                        // Estimate tspike here :
		 m1 = function2(t,v0,dt,geuler[i],&v0t,tspike,n);    // Recalibration of the membrane potential for modified euler:
		 v1 = v0t+dt*m1; 
		 G[i] = pow((dt-tspike)/tau,5)*exp(-(dt-tspike)/tau);  // Function to calculate decay of a jump for m=5 :
      }
                
		 euler[i] = v1;   // Reset :
            
               		  
      } 
      
        for(i=0;i<=n-1;i++)  // loop over all the neurons :
        {
         for(k=0;k<=n-1;k++)  // loop over all the jumps the ith neuron receives :
          {
             
              geuler[i] = geuler[i]+s[abs(i-k)]*G[k];
                            
           }
        } 
               
	return;
}

**Comment by dilawar** [comment]
We need to discuss this in person. If possible can you use GSL library from GNU for RG methods. http://www.gnu.org/software/gsl/

**Comment by Vanitha83** [comment]
Above is the incomplete version of the code and need to be revised completely. Is it possible to meet up in person?

**Comment by Vanitha83** [comment]
Above is the code for modified euler for finding spike time estimation and error analysis. I have an issue that at the end of each iteration the error value take some random value, though the code is error free.

**Comment by Vanitha83** [comment]
This issue is solved and can be closed now
