### ISSUE TITLE
Convergence with slope for different synaptic conductances

### ISSUE THREAD

**Issue by Vanitha83** [Vanitha83/CompAlgorithms#7]
![2](https://cloud.githubusercontent.com/assets/6986551/8107549/ae720228-107c-11e5-9cab-8bfc4ff3d569.png)

**Comment by Vanitha83** [comment]
This figure should be uploaded in the master branch

**Comment by bewantbe** [comment]
Looks like that the curve approaches to a line only for very small dt (dt<=0.001). What about dt around 0.1 ?

**Comment by Vanitha83** [comment]
Yes, for 1 ms,  I will upload all the figures for different schemes , various 'm' values and will be back to your question..

**Comment by Vanitha83** [comment]
Modified RK4 : m=3 
![3](https://cloud.githubusercontent.com/assets/6986551/8124956/9d43de26-1113-11e5-8eb6-311fe01f8cc0.png)

**Comment by Vanitha83** [comment]
#Modified RK4 : m=2
![4](https://cloud.githubusercontent.com/assets/6986551/8125019/3f203532-1114-11e5-93ef-8fdd5ce69340.png)

**Comment by Vanitha83** [comment]
Modified RK4 : m=5 :
![5](https://cloud.githubusercontent.com/assets/6986551/8125029/5c966474-1114-11e5-9b8d-33caa0e441ce.png)

**Comment by Vanitha83** [comment]
*Modified RK4 : m=1 and 2 (merged)
![12](https://cloud.githubusercontent.com/assets/6986551/8125052/b952d832-1114-11e5-8897-00891d11485a.png)

**Comment by Vanitha83** [comment]
@bewantbe Covergence order has been checked for modified RK4 for different synaptic time courses and the uploaded figures are Error as a function of time-step. In a new issue, the results for different numerical schemes for fixed value of m, say m=5 are uploaded. Coming back to your question, for dt=0.1, I have to run the code again but can be done in the few weeks ahead as currently I am focusing on another work.

**Comment by bewantbe** [comment]
Fine. Before I thought the unit of dt is ms, so I ask that question. It's second in your cases right?
