### ISSUE TITLE
Convergence is missing

### ISSUE THREAD

**Issue by Vanitha83** [Vanitha83/CompAlgorithms#9]
@bewantbe For poisson input, the convergence plot shows randomness. RandomSeed should be fixed. However, I have used srand((int)time(0)). As a first step, for poisson input, I have generated uniform random numbers between 0 and 1 and this has been used in the quantile for the exponential distribution. still it fails.(#poisson1.c)

**Comment by Vanitha83** [comment]
Solved and closing this issue..

**Comment by Vanitha83** [comment]
@bewantbe
![poisson1](https://cloud.githubusercontent.com/assets/6986551/8148081/e18b7dd2-12bc-11e5-960c-ff73e5518224.png)

RandomSeed is fixed.
#define RandomSeed srand(10)
#Generating random numbers b/w 0 and 1:
double unifRand(int i, double x)
{
    double random;
    double lambda; // smaller values of lambda gives flat distribution???? :
    lambda = 500;
    for(i=0;i<1000;i++)
    {  
        
       random = rand()/double(RAND_MAX); // Generate a uniform random number b/w 0 and 1 :
       //printf("%lf\n",random);
       x = log10(1-random)/(-lambda); // x is a random number with an exp. distribution :
       //printf("%lf\n",x);
     
    } 
    
     return x; 
}
The output of the above function is given as input to the neuron, still the convergence is failing.. Can you look up??

**Comment by bewantbe** [comment]
So... as I asked last time, how you calculate the error?

**Comment by Vanitha83** [comment]
@bewantbe 

*Error(dt)=(1/N) \sum_{j} | v_{dt}^{j}  -  v_{c}^{j}) |

*v_{dt} : Error from the mrk4 for dt 
*v_{c} : Error from the same mrk4 scheme but with small time step, in my code this 1.5625 x 10^{-6} seconds. 

code is under poisson1.c. Reference 1.

**Comment by bewantbe** [comment]
oh, so it is averaged error along whole time course.
you may try comparing v_{dt} and v_{c} by your eye (output and plot them), then see if there is something wrong.

**Comment by Vanitha83** [comment]
Didn't get you. ..can you frame the explanation clearly. .what do you mean by  "your eye "

**Comment by Vanitha83** [comment]
May be you meant the following? "plot both the errors separately to check where it goes wrong "

**Comment by Vanitha83** [comment]
code has to be rewritten using the following.

Test for single neuron for different "dt"
t_new=t_old - ln(xrand)/lambda.
This issue can be closed till then.

**Comment by dilawar** [comment]
Where is my pizza? 
On 16-Jun-2015 12:00 pm, Vanitha <notifications@github.com> wrote:Closed #9.
